version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    ports:
      - "3000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb:2.7.5
    container_name: influxdb
    restart: always
    ports:
      - "8089:8086"
    volumes:
      - influxdb-volume:/var/lib/influxdb
  postgres:
    image: postgres:15
    container_name: postgres
    restart: alway
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
  postgres-volume: # This line is added to declare the postgres-volume
    external: true




