interval: 10.
window_size: 0.1
snr: 10.
default_pulse: 1.33333333
airspyPath: "/home/pi/software/vhf_grc/airspy4_nogui.py"
outputFile: "/home/pi/vhf_data.yaml"
wavFilePath: "/mnt/data/local"
filename: "%Y%m%d-%H%M%S_atkaSPOT_vhf_{device}_{name}.wav"
influx:
  ip: "10.105.93.161"
  port: 8086
  database: "vhf"
receiver_blacklist: []
transmitter_blacklist: ["960",]
receivers:
  - name: "756W"
gains: [60,90]
transmitters:
  -   name: LAMP
      frequency: 150500000
      type: test
      serial: 148625
      pulse: 1.34
  -   name: "0041"
      frequency: 148010000
      type: new
      serial: 256641
      pulse: 1.644
  -   name: "bigb"
      frequency: 149213000
      type: bullet
      serial: 112386
      pulse: 1.0
  #-   name: "42"
      #frequency: 148230000
      #type: new
      #serial: 256642
      #pulse: 1.635
  #-   name: "43"
      #frequency: 148470000
      #type: new
      #serial: 256643
      #pulse: 1.63333
  #-   name: "44"
      #frequency: 148632000
      #type: new
      #serial: 256644
      #pulse: 1.642
  #-   name: "45"
      #frequency: 148830000
      #type: new
      #serial: 256645
      #pulse: 1.635
  #-   name: "46"
      #frequency: 150029000
      #type: new
      #serial: 256646
      #pulse: 1.590
  #-   name: "47"
      #frequency: 150228000
      #type: new
      #serial: 256647
      #pulse: 1.596
  #-   name: "48"
      #frequency: 150429000
      #type: new
      #serial: 256648
      #pulse: 1.634
  #-   name: "49"
      #frequency: 150630000
      #type: new
      #serial: 256649
      #pulse: 1.621
  #-   name: "50"
      #frequency: 150832000
      #type: new
      #serial: 256650
      #pulse: 1.628
  #-   name: "51"
      #frequency: 151140000
      #type: new
      #serial: 256651
      #pulse: 1.585
  #-   name: "52"
      #frequency: 151340000
      #type: new
      #serial: 256652
      #pulse: 1.654
  #-   name: "53"
      #frequency: 151739000
      #type: new
      #serial: 256653
      #pulse: 1.644
  #-   name: "54"
      #frequency: 151940000
      #type: new
      #serial: 256654
      #pulse: 1.602
  #-   name: "600"
      #frequency: 150600000
      #type: old
      #serial: NA
      #pulse: 1.594
  #-   name: "640"
      #frequency: 150640000
      #type: old
      #serial: NA
      #pulse: 1.561
  #-   name: "710"
      #frequency: 150710000
      #type: old
      #serial: NA
      #pulse: 1.536
  #-   name: "760"
      #frequency: 150760000
      #type: old
      #serial: NA
      #pulse: 1.56
  #-   name: "820"
      #frequency: 150820000
      #type: old
      #serial: NA
      #pulse: 1.505
  #-   name: "960"
      #frequency: 150960000
      #type: old
      #serial: NA
      #pulse: NA
